### ISSUE TITLE
thoughtful article backing the "Chinazi " term

### ISSUE THREAD

**Issue by ckhung** [cirosantilli/china-dictatorship#102]
[這麼好的人民，不倒點霉都對不起他們](https://www.bannedbook.org/bnews/zh-tw/baitai/20190816/1175647.html)
This article by 押沙龍 does not mention the term "Chinazi" . It does not even talk about CCP. It simlpy describes how Nazi brain-washed its people. And the original post was of course censored by CCP.

**Comment by cirosantilli** [comment]
Thanks for the link Chao-Kuei, added under nazi section 4d4c7a2f708ceeedb1d46e7703be3926d1996fe6

A few things I've been curious about:

- how does Caixin not get shut down?
- is it known who is behind bannedbook.org?

**Comment by cirosantilli** [comment]
OK, bannedbook.org is a Falun Gong media: https://github.com/cirosantilli/china-dictatorship/tree/15b9b40e175e89b693bba273675404c65ea44e84#bannedbook-org

**Comment by ckhung** [comment]
I must admit that very often I don't spend enough time researching the ultimate source of articles like you do :-) I read this Nazi article by yashalong some months ago. Later I frequently recommend it to people. Instead of finding the original link that I keep somewhere, most often I just get lazy and google it and find it all over different places :-) Right now I finally grep'ed the files in my computer and find the link: http://www.theintellectual.net/zh/hong-kong-and-macao-drip/regulus-tea-room/1764-such-a-good-people-do-not-hesitate-to-be-sorry-for-them-source-absalom-39-s-blog.html  It says that the article was from yashalong's blog without giving a link. Googling "押沙龍 博客" gets me to the old one  http://blog.sina.com.cn/s/articlelist_1427021624_0_1.html and the new one http://yashalong.blog.caixin.com/ Trying to recall, I probably believed it was censored because I didn't find the new blog and didn't find the article in the old blog. Anyway you have now found the same article in yashalong's new blog, I take back my words that it is censored.
