### ISSUE TITLE
称赞？？别搞错了？我用中文写，如果你是中国人的话，你应该看得懂，如果不是，那就请你闭嘴！

### ISSUE THREAD

**Issue by Xerrors** [cirosantilli/china-dictatorship#117]
你是中国人吗？？

你以为你在网络上了解的只言片语就能代表这个世界了？

不知道应该说是坏，还是应该说你天真？

说真的，你真的太幼稚了，不知道 有没有接受过九年义务教育？？

上面是基于你是个人的角度写的

---

如果你是一个组织的话，我想说，你们的交易真的很肮脏，我对你们的价值观表示鄙视！！(╬▔皿▔)凸

：）

**Comment by cirosantilli** [comment]
Hi Xerrors,

- https://github.com/cirosantilli/china-dictatorship/tree/00ddcca46fd386016af1ffa4d2a8edb7393f4fc6#is-ciro-santilli-chinese
- https://github.com/cirosantilli/china-dictatorship/tree/00ddcca46fd386016af1ffa4d2a8edb7393f4fc6#not-chinese
- https://github.com/cirosantilli/china-dictatorship/tree/00ddcca46fd386016af1ffa4d2a8edb7393f4fc6#cia-funding
