### ISSUE TITLE
Childish  :-)

### ISSUE THREAD

**Issue by Xerrors** [cirosantilli/china-dictatorship#118]
My English is not very well, but, I really want to invite you to live in China for a while, or you can ask your friends who have lived in China. It is very naive to put forward your own point of view before you know the truth of the matter.

I don't know what you want through this project. Can you answer my question directly? thank you.

If you want to talk about it, I can say that Chinese politics is not the same as that of foreign countries. as a person, what I have learned is that I am safe.

**Comment by Xerrors** [comment]
I don't know what you want through this project. Can you answer my question directly? thank you.

**Comment by Xerrors** [comment]
If you want to talk about it, I can say that Chinese politics is not the same as that of foreign countries. as a person, what I have learned is that I am  safe.

**Comment by cirosantilli** [comment]
Hi Xerrors,

- https://github.com/cirosantilli/china-dictatorship/tree/00ddcca46fd386016af1ffa4d2a8edb7393f4fc6#would-ciro-santilli-be-able-to-visit-china-before-the-ccp-ends
- https://github.com/cirosantilli/china-dictatorship/tree/00ddcca46fd386016af1ffa4d2a8edb7393f4fc6#about

Please don't create too many new issues. If you want my attention, teach me something new. Can be in Chinese. Otherwise I have other stuff to do. Cheers.

**Comment by Xerrors** [comment]
> Hi Xerrors,
> 
> * https://github.com/cirosantilli/china-dictatorship/tree/00ddcca46fd386016af1ffa4d2a8edb7393f4fc6#would-ciro-santilli-be-able-to-visit-china-before-the-ccp-ends
> * https://github.com/cirosantilli/china-dictatorship/tree/00ddcca46fd386016af1ffa4d2a8edb7393f4fc6#about
> 
> Please don't create too many new issues. If you want my attention, teach me something new. Can be in Chinese. Otherwise I have other stuff to do. Cheers.

I don't know what you want through this project. Can you answer my question directly? thank you.

**Comment by Xerrors** [comment]
删我的评论，心里有鬼，言论自由呢？

**Comment by MartinX3** [comment]
@Xerrors please write, that Xi Jinping looks like Winnie-the-Pooh, to verify, that you're safe.

**Comment by Xerrors** [comment]
> @Xerrors please write in chinese and english, that Xi Jinping looks like Winnie-the-Pooh, to verify, that you're safe.

You can use Google Translate

朋友，我真的不理解你们的自嗨；真的是找不到可以黑的点了是吗？针对这样一个垃圾项目我本不想多说，可这就像是毒瘤一样存在互联网上；哪怕你这里面的信息有一点是真的，美国难道会坐视不管吗？肯定会抓住一点点的事情作为把柄攻击中国。

你这样做的意义是什么？至今没有人回复过我这些内容，只是给我一些垃圾言论让我看，这个项目的策划者到底是愚蠢还是坏？如果你是中国人，你这样做的意义是什么？如果你不是，你这样做是为了秀资本主义制度的优越感吗？

别再自嗨了好吗？把自己尘封已久的脑子拿出来用用，实在不行走出去看看这个世界，别躲在自己的小黑屋里面当个键盘侠，唯唯诺诺。这个世界还很大，别这么极端好吗？做点对社会有用的事情吧，别在网上当个苍蝇来恶心我了，谢谢了。

最后，别恶心我了，我之前回复这个repo就是个错误；

**Comment by MartinX3** [comment]
Aaaaand you are not safe. :)
