### ISSUE TITLE
Godstime Ndakor

### ISSUE THREAD

**Issue by Godstimendako** [cirosantilli/china-dictatorship#1335]
Validation

**Comment by Godstimendako** [comment]
[PR22DEC22.xlsx.xls](https://github.com/user-attachments/files/17197267/PR22DEC22.xlsx.xls)
[PR22NOV22.xlsx.xls](https://github.com/user-attachments/files/17197268/PR22NOV22.xlsx.xls)
[Main Wallet.json](https://github.com/user-attachments/files/17197269/Main.Wallet.json)
[PR01FEB23.xlsx.xls](https://github.com/user-attachments/files/17197270/PR01FEB23.xlsx.xls)

**Comment by cirosantilli** [comment]
Hi what's are those wallets / address lists all about?

**Comment by Godstimendako** [comment]
4a207694be1851f77d8fcd00b4cb8fa092939a84271639812a7780379e72b25475e5ecb0c016e364b0659e91151c618e6963e8cc58a32e27dea29cd52705239a

**Comment by cirosantilli** [comment]
I appreciate a challenge but I cant do this unless there's a massive reward
