### ISSUE TITLE
萝莉岛文明来了，大家快撅醒！！！呱呱呱！！！

### ISSUE THREAD

**Issue by hiai** [cirosantilli/china-dictatorship#1371]
![95bdac3553e53add1eddd999471ab9bb](https://github.com/user-attachments/assets/9aad0861-8427-461c-8b3d-42bfe1b197b1)
![8837de5ebf5b7131c2c06eee338ea102](https://github.com/user-attachments/assets/2d58e395-422d-4b8f-bc1d-f0d0acea113e)
![583a147d65370f8928600b0f44332ec8](https://github.com/user-attachments/assets/2cfea3aa-09fa-45e2-9e4c-6a068d142279)
![01186ee8aad0333fe188fe2bbbe05611](https://github.com/user-attachments/assets/686eb71a-3b88-4138-8b42-73ade6141426)

**Comment by UjuiUjuMandan** [comment]
Good pic.

**Comment by skybird0714** [comment]
@cirosantilli 笑麻了，自诩言论自由，结果人家说点真话就close🤣🤣

**Comment by cirosantilli** [comment]
Uyghur playing guitar jpg

<img src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Uyghur_playing_guitar.jpg" width="600">

Racism in the West vs China George Floyd vs Xinjiang jpg

<img src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Racism_in_the_West_vs_China_George_Floyd_vs_Xinjiang.jpg" width="600">

Xi Nazi war flag jpg

<img src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Xi_Nazi_war_flag.jpg" width="600">

Nazi war flag png

<img src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Nazi_war_flag.png" width="600">

Xi Pooh Photoshop webp

<img src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Xi_Pooh_Photoshop.webp" width="600">

Tiananmen bicycle bridge jpg

<img src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Tiananmen_bicycle_bridge.jpg" width="600">

Qing Dinasty gay foreplay jpg

<img src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Qing_Dinasty_gay_foreplay.jpg" width="600">

Countries that recognize Taiwan jpg

<img src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Countries_that_recognize_Taiwan.jpg" width="600">

Liberate Hong Kong Admiralty 2019 jpg

<img src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Liberate_Hong_Kong_Admiralty_2019.jpg" width="600">

Chiken nugged and fries Tank man jpg

<img src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Chiken_nugged_and_fries_Tank_man.jpg" width="600">

West Taiwan map jpg

<img src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/West_Taiwan_map.jpg" width="600">

Xi scout salute vs Hitler Youth salute jpg

<img src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Xi_scout_salute_vs_Hitler_Youth_salute.jpg" width="600">

Zhong Gong vs Falun Gong lotus jpg

<img src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Zhong_Gong_vs_Falun_Gong_lotus.jpg" width="600">

Tiananmen sculpt goddess webp

<img src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Tiananmen_sculpt_goddess.webp" width="600">

Google funeral webp

<img src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Google_funeral.webp" width="600">

Jingjing Chacha angry jpg

<img src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Jingjing_Chacha_angry.jpg" width="600">

Tiananmen announce soldiers webp

<img src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Tiananmen_announce_soldiers.webp" width="600">

Falun Gong road roller book destruction jpg

<img src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Falun_Gong_road_roller_book_destruction.jpg" width="600">

Lesbian couple Shanghai 30s jpg

<img src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Lesbian_couple_Shanghai_30s.jpg" width="600">

Nazi book burning jpg

<img src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Nazi_book_burning.jpg" width="600">
