### ISSUE TITLE
你怎么不练起来法轮功呢

### ISSUE THREAD

**Issue by horseson2018** [cirosantilli/china-dictatorship#161]
21世纪还有信超能力的，哈皮

**Comment by cirosantilli** [comment]
I don't understand what you mean.

**Comment by horseson2018** [comment]
> Hi horseson2018,
> 
> I don't understand what you mean, are you talking about Falun Gong? If so, don't be a pussy, and say the word, answer at:
> 
> https://github.com/cirosantilli/china-dictatorship/tree/6fb636e05de9f32242c82dfd5c70f06ef580dcf4#does-ciro-santilli-believe-in-or-practice-falun-gong

Do you know some falungong followers burned themselves at Tiananmen in 2001.1.23?

**Comment by ChanlingXianjun** [comment]
神奇的轮子
