### ISSUE TITLE
What the heck is this? 

### ISSUE THREAD

**Issue by YUFENGWANG** [cirosantilli/china-dictatorship#163]

**Comment by cirosantilli** [comment]
Hi YUFENGWANG,

https://github.com/cirosantilli/china-dictatorship/tree/4008147d15960f4e740782c466faa55f54579ed9#shitpost

![](https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Shit.jpg)

**Comment by YUFENGWANG** [comment]
*** you.
