### ISSUE TITLE
正当殺人 https://www.pixiv.net/artworks/85005795

### ISSUE THREAD

**Issue by ghost** [cirosantilli/china-dictatorship#176]
![85005795_p0_master1200](https://user-images.githubusercontent.com/76736790/103286993-5b864d00-4a1c-11eb-8e25-e28061850d0e.jpg)

**Comment by cirosantilli** [comment]
Hi kill-ciro-santilli UID 76736790

![](https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Xi_Pooh_Obama.webp)
