### ISSUE TITLE
反日中国製品使用悪質不潔肥満豚Ciro Santilli https://www.pixiv.net/artworks/86079907

### ISSUE THREAD

**Issue by ghost** [cirosantilli/china-dictatorship#177]
![Screenshot_20201229-212243-1](https://user-images.githubusercontent.com/76736790/103287005-62ad5b00-4a1c-11eb-9c53-379d39604601.jpg)

**Comment by cirosantilli** [comment]
Hi kill-ciro-santilli UID 76736790

![](https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Xi_Pooh_Obama.webp)
