### ISSUE TITLE
GitHub will not be blocked by GFW because the Chinese people are constantly fighting for democracy. I found some video materials, hope to help you.

### ISSUE THREAD

**Issue by ghost** [cirosantilli/china-dictatorship#179]
https://github.com/hinata-daisuki/danmaku/blob/main/av80976236/av80976236_1.mp4?raw=true
https://github.com/hinata-daisuki/danmaku/blob/main/av80976236/av80976236_2.mp4?raw=true
If you can, please back up these two videos to YouTube and attach a brief introduction of #165 . I hope this to help you.

**Comment by cirosantilli** [comment]
Hi democracy-topic, thanks for the links.
