### ISSUE TITLE
You suck | 什么狗屁玩意

### ISSUE THREAD

**Issue by ccz666** [cirosantilli/china-dictatorship#193]
this project is a total shit,hitgub should not be used like this
|
爬 资本主义分裂中国之心不死 想想苏联老大哥怎么走的

**Comment by cirosantilli** [comment]
Hi ccz666,

> this project is a total shit,hitgub should not be used like this
> |
> 爬 资本主义分裂中国之心不死 想想苏联老大哥怎么走的

https://unix.stackexchange.com/questions/29608/why-is-it-better-to-use-usr-bin-env-name-instead-of-path-to-name-as-my
