### ISSUE TITLE
There should be more comparison.

### ISSUE THREAD

**Issue by Alex-Hou** [cirosantilli/china-dictatorship#34]
Please add some information about [Julian Assange](https://en.wikipedia.org/wiki/Julian_Assange) and [Edward Snowden](https://en.wikipedia.org/wiki/Edward_Snowden), Just let people see what US government did to them, to the whole world.
The government of different countries ruled people in different ways, and the harm they made is the same.
No freedom of the press? People won't know some things that government wants to hide.
But did people in the US have it? All they got is just thousands of Fake news.
And what if "communism" is not like what you thought?
The gov betrayed the "-ism" thing, doesn't mean it's originally like that.
Human beings must create something new to stop the dispute of ideology, and focus on building common well-being.

**Comment by cirosantilli** [comment]
Hi Alex,

https://github.com/cirosantilli/china-dictatorship/tree/d2a0ca4f1c27de070ec4a2c8126609ec12a59b95#western-democracies-are-not-perfect
