### ISSUE TITLE
还敢在假点吗？中华民族是最团结的民族，走狗就不要想要挑起内斗了，华夏命运共同体岂是你能理解的？

### ISSUE THREAD

**Issue by 15538339968** [cirosantilli/china-dictatorship#358]
还敢在假点吗？中华民族是最团结的民族，走狗就不要想要挑起内斗了，华夏命运共同体岂是你能理解的？

**Comment by 15538339968** [comment]
> 还敢在假点吗？中华民族是最团结的民族，走狗就不要想要挑起内斗了，华夏命运共同体岂是你能理解的？

**Comment by lichl9968** [comment]
> 您好 15538339968，
> 
> > 还敢在假点吗？中华民族是最团结的民族，走狗就不要想挑起内斗了，华夏命运共同体是你能理解的吗？
> > 还敢在假点吗？中华民族是最团结的民族，走狗就不要想挑起内斗了，华夏命运共同体是你能理解的吗？
> 
> 坦克人 jpg
> 
> <img alt="" width="600" src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Tank_Man.jpg">
> 
> 天安门女同志之吻jpg
> 
> <img alt="" width="600" src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Tiananmen_lesbian_kiss.jpg">
> 
> 饺子.jpg
> 
> <img alt="" width="600" src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Jiaozi.jpg">
> 
> Blood Cotton Initiative by Wuheqilin holocaust denial jpg
> 
> <img alt="" width="600" src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Blood_Cotton_Initiative_by_Wuheqilin_holocaust_denial.jpg">
> 
> Tank Man ducks jpg
> 
> <img alt="" width="600" src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Tank_Man_ducks.jpg">
> 
> Tiananmen bicycle bridge jpg
> 
> <img alt="" width="600" src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Tiananmen_bicycle_bridge.jpg">
> 
> Wujiao png
> 
> <img alt="" width="600" src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Wujiao.png">
> 
> Nikolai Yezhov Stalin canal edit webp
> 
> <img alt="" width="600" src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Nikolai_Yezhov_Stalin_canal_edit.webp">
> 
> Pokemon political meme little pink super effective png
> 
> <img alt="" width="600" src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Pokemon_political_meme_little_pink_super_effective.png">
> 
> Mao coffin jpeg
> 
> <img alt="" width="600" src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Mao_coffin.jpeg">
> 
> Xi Pooh Photoshop webp
> 
> <img alt="" width="600" src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Xi_Pooh_Photoshop.webp">
> 
> Tiananmen sea jpg
> 
> <img alt="" width="600" src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Tiananmen_sea.jpg">
> 
> Last Supper arrest jpeg
> 
> <img alt="" width="600" src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Last_Supper_arrest.jpeg">
> 
> Mei with Hong kong jpg
> 
> <img alt="" width="600" src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Mei_with_Hong_kong.jpg">
> 
> United China Relief 3 million Chinese jpg
> 
> <img alt="" width="600" src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/United_China_Relief_3_million_Chinese.jpg">
> 
> Zoom Boris jpg
> 
> <img alt="" width="600" src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Zoom_Boris.jpg">
> 
> Tiananmen helmet jpg
> 
> <img alt="" width="600" src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Tiananmen_helmet.jpg">
> 
> Tiananmen message board cleanup webp
> 
> <img alt="" width="600" src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Tiananmen_message_board_cleanup.webp">
> 
> Falun Gong magic fungi jpg
> 
> <img alt="" width="600" src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Falun_Gong_magic_fungi.jpg">
> 
> Ciro Santilli png
> 
> <img alt="" width="600" src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Ciro_Santilli.png">

The Chinese nation is the most united nation. Dogs don't want to provoke internal strife. Can you understand the community of Chinese destiny?

**Comment by yters** [comment]
A unity where you have to kill all dissenters is not a very good
unity.  It only means the division is hidden.  It also means the
culture becomes stagnant because everyone is too afraid to think for
themselves, just like in the Soviet Union before its collapse.

**Comment by MisakaSakura** [comment]
> A unity where you have to kill all dissenters is not a very good
> unity.  It only means the division is hidden.  It also means the
> culture becomes stagnant because everyone is too afraid to think for
> themselves, just like in the Soviet Union before its collapse.
> 
> On 6/8/21, coolBoy ***@***.***> wrote:
> >> 您好 15538339968，
> 
> >>
> 
> >> > 还敢在假点吗？中华民族是最团结的民族，走狗就不要想挑起内斗了，华夏命运共同体是你能理解的吗？
> 
> >> > 还敢在假点吗？中华民族是最团结的民族，走狗就不要想挑起内斗了，华夏命运共同体是你能理解的吗？
> 
> >>
> 
> >> 坦克人 jpg
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Tank_Man.jpg">
> 
> >>
> 
> >> 天安门女同志之吻jpg
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Tiananmen_lesbian_kiss.jpg">
> 
> >>
> 
> >> 饺子.jpg
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Jiaozi.jpg">
> 
> >>
> 
> >> Blood Cotton Initiative by Wuheqilin holocaust denial jpg
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Blood_Cotton_Initiative_by_Wuheqilin_holocaust_denial.jpg">
> 
> >>
> 
> >> Tank Man ducks jpg
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Tank_Man_ducks.jpg">
> 
> >>
> 
> >> Tiananmen bicycle bridge jpg
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Tiananmen_bicycle_bridge.jpg">
> 
> >>
> 
> >> Wujiao png
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Wujiao.png">
> 
> >>
> 
> >> Nikolai Yezhov Stalin canal edit webp
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Nikolai_Yezhov_Stalin_canal_edit.webp">
> 
> >>
> 
> >> Pokemon political meme little pink super effective png
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Pokemon_political_meme_little_pink_super_effective.png">
> 
> >>
> 
> >> Mao coffin jpeg
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Mao_coffin.jpeg">
> 
> >>
> 
> >> Xi Pooh Photoshop webp
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Xi_Pooh_Photoshop.webp">
> 
> >>
> 
> >> Tiananmen sea jpg
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Tiananmen_sea.jpg">
> 
> >>
> 
> >> Last Supper arrest jpeg
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Last_Supper_arrest.jpeg">
> 
> >>
> 
> >> Mei with Hong kong jpg
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Mei_with_Hong_kong.jpg">
> 
> >>
> 
> >> United China Relief 3 million Chinese jpg
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/United_China_Relief_3_million_Chinese.jpg">
> 
> >>
> 
> >> Zoom Boris jpg
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Zoom_Boris.jpg">
> 
> >>
> 
> >> Tiananmen helmet jpg
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Tiananmen_helmet.jpg">
> 
> >>
> 
> >> Tiananmen message board cleanup webp
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Tiananmen_message_board_cleanup.webp">
> 
> >>
> 
> >> Falun Gong magic fungi jpg
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Falun_Gong_magic_fungi.jpg">
> 
> >>
> 
> >> Ciro Santilli png
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Ciro_Santilli.png">
> 
> >
> 
> > The Chinese nation is the most united nation. Dogs don't want to provoke
> > internal strife. Can you understand the community of Chinese destiny?
> 
> >
> 
> > --
> 
> > You are receiving this because you are subscribed to this thread.
> 
> > Reply to this email directly or view it on GitHub:
> 
> > https://github.com/cirosantilli/china-dictatorship/issues/358#issuecomment-856562413
> 

这不代表你可以拿亲妈造谣，哦你没妈啊，那没事了，你们这种傻逼知道自己的西方世界是怎么对付异见者的吗？黑中国就是政治正确的环境好意思来对我们指指点点

**Comment by MisakaSakura** [comment]
> A unity where you have to kill all dissenters is not a very good
> unity.  It only means the division is hidden.  It also means the
> culture becomes stagnant because everyone is too afraid to think for
> themselves, just like in the Soviet Union before its collapse.
> 
> On 6/8/21, coolBoy ***@***.***> wrote:
> >> 您好 15538339968，
> 
> >>
> 
> >> > 还敢在假点吗？中华民族是最团结的民族，走狗就不要想挑起内斗了，华夏命运共同体是你能理解的吗？
> 
> >> > 还敢在假点吗？中华民族是最团结的民族，走狗就不要想挑起内斗了，华夏命运共同体是你能理解的吗？
> 
> >>
> 
> >> 坦克人 jpg
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Tank_Man.jpg">
> 
> >>
> 
> >> 天安门女同志之吻jpg
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Tiananmen_lesbian_kiss.jpg">
> 
> >>
> 
> >> 饺子.jpg
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Jiaozi.jpg">
> 
> >>
> 
> >> Blood Cotton Initiative by Wuheqilin holocaust denial jpg
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Blood_Cotton_Initiative_by_Wuheqilin_holocaust_denial.jpg">
> 
> >>
> 
> >> Tank Man ducks jpg
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Tank_Man_ducks.jpg">
> 
> >>
> 
> >> Tiananmen bicycle bridge jpg
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Tiananmen_bicycle_bridge.jpg">
> 
> >>
> 
> >> Wujiao png
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Wujiao.png">
> 
> >>
> 
> >> Nikolai Yezhov Stalin canal edit webp
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Nikolai_Yezhov_Stalin_canal_edit.webp">
> 
> >>
> 
> >> Pokemon political meme little pink super effective png
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Pokemon_political_meme_little_pink_super_effective.png">
> 
> >>
> 
> >> Mao coffin jpeg
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Mao_coffin.jpeg">
> 
> >>
> 
> >> Xi Pooh Photoshop webp
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Xi_Pooh_Photoshop.webp">
> 
> >>
> 
> >> Tiananmen sea jpg
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Tiananmen_sea.jpg">
> 
> >>
> 
> >> Last Supper arrest jpeg
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Last_Supper_arrest.jpeg">
> 
> >>
> 
> >> Mei with Hong kong jpg
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Mei_with_Hong_kong.jpg">
> 
> >>
> 
> >> United China Relief 3 million Chinese jpg
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/United_China_Relief_3_million_Chinese.jpg">
> 
> >>
> 
> >> Zoom Boris jpg
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Zoom_Boris.jpg">
> 
> >>
> 
> >> Tiananmen helmet jpg
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Tiananmen_helmet.jpg">
> 
> >>
> 
> >> Tiananmen message board cleanup webp
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Tiananmen_message_board_cleanup.webp">
> 
> >>
> 
> >> Falun Gong magic fungi jpg
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Falun_Gong_magic_fungi.jpg">
> 
> >>
> 
> >> Ciro Santilli png
> 
> >>
> 
> >> <img alt="" width="600"
> >> src="https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master/Ciro_Santilli.png">
> 
> >
> 
> > The Chinese nation is the most united nation. Dogs don't want to provoke
> > internal strife. Can you understand the community of Chinese destiny?
> 
> >
> 
> > --
> 
> > You are receiving this because you are subscribed to this thread.
> 
> > Reply to this email directly or view it on GitHub:
> 
> > https://github.com/cirosantilli/china-dictatorship/issues/358#issuecomment-856562413
> 

you right,I cant breathe.
