### ISSUE TITLE
set up needs help

### ISSUE THREAD

**Issue by yeinenterprice** [cirosantilli/china-dictatorship#381]
I want to run the source on my site,But I have some issues,my English is not really good so,can you say more clear that how can i build it.

**Comment by cirosantilli** [comment]
Have a look at: https://github.com/cirosantilli/china-dictatorship/tree/ece35cb8d76c69541d1f7d5511da6bf481b4980f#mirrors First make sure you can build locally, then I use `./push` to push to github pages.

**Comment by yeinenterprice** [comment]
> Have a look at: https://github.com/cirosantilli/china-dictatorship/tree/ece35cb8d76c69541d1f7d5511da6bf481b4980f#mirrors First make sure you can build locally, then I use `./push` to push to github pages.

Thanks man, awesome project,good work
