### ISSUE TITLE
Please delete and block this guy's spamming,ciro.

### ISSUE THREAD

**Issue by yeinenterprice** [cirosantilli/china-dictatorship#492]

**Comment by cirosantilli** [comment]
I block them myself one by one. No need to delete anybody's accounts. Little pinks are the essence of this repo.

**Comment by yeinenterprice** [comment]
> I block them myself one by one as needed. No need to delete anybody's accounts. Little pinks are the essence of this repo.

确实，小粉红和五毛只会让中共加速灭亡，我们帮他们清醒反而是在帮中共
