### ISSUE TITLE
A section about the extradition law admendment

### ISSUE THREAD

**Issue by VincentTam** [cirosantilli/china-dictatorship#59]
A short interview with Chris Patten, the last colonial governor of HK, about the extradition law: https://youtu.be/dEvalUQuClE

"If we can't trust the PRC's promise made in the Joint Declarations about HK's autonomy, on what can we trust her?"

The Bill would put HK's judicial independence in peril and enable HK government to handle suspects to the mainland.  This law admendment has faced local and international opposition.  Many fears the extension of PRC's dictatorship to HKSAR: one, regardless of nationality, can be arrested in HK for arbitrary accusations made by the mainland, where the authorities rule *by* law.

Btw, I seize this chance to mention a [petition to revoke HK Chief Executive Carrie Lam's *Légion d'Honneur*](https://www.change.org/p/the-grand-chancery-of-the-legion-of-honor-revoke-hong-kong-chief-executive-carrie-lam-s-legion-of-honor-distinction-1401f615-a42b-4485-9cd2-5a7cab597c8c?fbclid=IwAR1Kon9_PawjrezykT62b4CJ45Qfd8X8WG0cRBa_ZPlrwTxAics_WRAMTWU).

> "Lorsque qu'on perd son honneur de cette façon, on perd sa médaille qui va avec."
> "When one loses her honor like this, one loses her medal that comes with."  
> --- my French teacher

**Comment by cirosantilli** [comment]
Hi Vincent,

Mentioned in news at 93f0058314b7a5c7ec10d6aa6a4d2cc098f5b5a2

Countries keeping promises? A joke? :-)

Let's hope CCP ends before 2047!
