### ISSUE TITLE
Great Work!

### ISSUE THREAD

**Issue by Taylor-Hasterd** [cirosantilli/china-dictatorship#63]
Hi cirosantilli,

I first encountered you when I was searching something on Stackoverflow, and was caught by your username and image.

I am chinese and a student, and I hate especially the GFW, which greatly damages my internet experience. From china, many famous websites are extremely slow (e.g. GitHub, you can't image what it is having a speed of 10kb/s when you want to download something from GitHub).

Another thing I disgust is that the party does not value people's privacy and, generally, Human Rights. All information, even our personal files, are scanned using Chinese drives. One thing they teach us is that the sovereignty is higher than Human Rights, appearing in our textbooks, emerging from radios, and taking part in TV programs. I think that a country is built for people's happiness and rights, and without which, the country is not a successful country.

Moreover, I am interested in Computer Science, and want to be a programmer. However, I am very nervous and anxious for the 996 in China. Those terrible remarks said by capitalists like **Jack Ma**, **Richard Liu** really annoyed me. I also love video games, and hope that one day China will have its own 3A video game. But now the video game market in China is bad.

I am very happy seeing there are people who love China and have realized what the government has done. Works like this GitHub project coming from a selfless person who loves China as you is appreciated. My English is not very good, I can just repeat "Great Work" three times to express my feeling.
**_Great Work Great Work Great Work_**

I wish that one day the GFW will fall, and the people will be free, the Human Rights will be valued in China.

Thank you again for your excellent work, and wish you a good day!

**Comment by cirosantilli** [comment]
Taylor,

We are but minor waves in the great sea of politics,

If in our lives the Sun and Moon realign and the CCP falls, may we then ride this tsunami of joy,

Or else, be comforted that let the next generations will appreciate this inevitable victory,

All best!

**Comment by VincentTam** [comment]
@Taylor-Hasterd  
![Resistance dog](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTG3KMwPnxeOGeMWr50XV2DmGIEA2TCy5CdcwB0WCCDe3rgatgR)
