### ISSUE TITLE
你是中国人吗？？如果不是那别国的政治管你妈了个逼的事？？还有，你这种跳梁小丑别他妈污染github跟stackoverflow！！

### ISSUE THREAD

**Issue by loversInJapan** [cirosantilli/china-dictatorship#66]
你是中国人吗？？如果不是那别国的政治管你妈了个逼的事？？还有，你这种跳梁小丑别他妈污染github跟stackoverflow！！

**Comment by cirosantilli** [comment]
Hello,

https://github.com/cirosantilli/china-dictatorship/tree/43dffacee9da070154d9edaf2d0bac26c306e099#you-are-not-chinese-you-cant-interfere-in-chinese-politics

**Comment by loversInJapan** [comment]
The Chinese people is fine. We are having a happy life. Chinese govermemt is not bad as your thought. You should focus on what it has done for good to the people. And we don't need your concernt, so why don't you just mine your business. BTW, github is place to share code not for politics.

**Comment by firezdog** [comment]
Yeah -- I understand that people use git for other things like novels, but I prefer that Github be used to share code rather than as a forum to discuss politics.

**Comment by sonictl** [comment]
> Yeah -- I understand that people use git for other things like novels, but I prefer that Github be used to share code rather than as a forum to discuss politics.

Not only git, but also stackoverflow. Please do not put your political view in your profile on stackoverflow.

**Comment by cirosantilli** [comment]
Hi firezdog,

https://github.com/cirosantilli/china-dictatorship/tree/e02f919339a8bd3a3e4a3b44d79762a64ba2a5ed#you-are-using-stack-overflow-in-a-way-that-it-was-not-meant-to-be-used-so-what-you-are-doing-is-in-principle-wrong
