### ISSUE TITLE
您算哪根葱啊？毛长齐了吗？cnm

### ISSUE THREAD

**Issue by cuijianzhe** [cirosantilli/china-dictatorship#70]

**Comment by cirosantilli** [comment]
Hi cuijianzhe,

I think I am: https://cirosantilli.com/#ciro-santilli

**Comment by iTanken** [comment]
> _No description provided._

僟潪，適種芣帶臟茡哋摽趧⑴瘢哋迯國亾湜看芣董哋。
①羣洎顧芣叚、恬囨倁恥、臰芣婹臉、垍苡潙肆哋迯綁蠻夷洧什庅粢咯迀渉筗國哋禸蔀倳務。

**Comment by RCoeurjoly** [comment]
> > _No description provided._
> 
> 僟潪，適種芣帶臟茡哋摽趧⑴瘢哋迯國亾湜看芣董哋。
> ①羣洎顧芣叚、恬囨倁恥、臰芣婹臉、垍苡潙肆哋迯綁蠻夷洧什庅粢咯迀渉筗國哋禸蔀倳務。

是种不带脏字的标题， 一般的外国人是看不懂的。
自顾不暇恬不知耻，臭不要脸，自以为是外邦蛮夷有什么资格干涉中国的内部事物

一般来说，你开个Issue就是来表达你的意见。你用这种语言反而阻碍正常的交流。

**Comment by cirosantilli** [comment]
@RCoeurjoly see also [Proverbs 26:4](https://github.com/cirosantilli/china-dictatorship/tree/bcb4208cdfd740989c2aa7e2efc4584c683dbc57#what-is-your-reply-strategy).

**Comment by XiJingpingthePooh** [comment]
@cuijianzhe 在哪发表自己的想法是个人自由 你个共产狗快滚回你国

**Comment by cuijianzhe** [comment]
> @cuijianzhe 在哪发表自己的想法是个人自由 你个共产狗快滚回你国

滚回我国？ 你算什么东西啊？ 你脚底下踩得那个国家啊？ 你脑子里面全部是屎吧？

**Comment by cuijianzhe** [comment]
closed
