### ISSUE TITLE
纵然你有言论自由，也请不要在技术社区谈论此类问题，更不要用如此狭隘的想法视之他人，只会显得自己越发丑陋

### ISSUE THREAD

**Issue by iHen9** [cirosantilli/china-dictatorship#75]
认为自己做的什么都对，对于不了解的恶意诋毁，中国的文化不是基于宗教，何必将自己的想法强加于他人。看待问题请公正对待，而不是凌驾于他人之上，双标这种做法已经见怪不怪了，在技术社区看到这种东西真的有些恶心。

**Comment by XiJingpingthePooh** [comment]
在哪发表自己的想法是个人自由 你个共产狗快滚回你国

**Comment by cirosantilli** [comment]
Hi iHen9,

https://github.com/cirosantilli/china-dictatorship/tree/75356679ab6509aa6608804f57e9414bc347ff48#you-are-using-stack-overflow-in-a-way-that-it-was-not-meant-to-be-used-so-what-you-are-doing-is-in-principle-wrong

@XiJingpingthePooh thanks for the support, but keep it polite, or I'll block you.

**Comment by iHen9** [comment]
呵呵，既然是自由干嘛这样骂人呢，一个不尊重个人一个不敢继续直面。GitHub是当前人类共有的社区，不是你个low B的地盘，你没有这个权力让我离开。早就拉黑你了，近期看到被一个鬼关注了，就找过来了，告诉你们，来一个拉黑一个。

**Comment by iHen9** [comment]
> 在哪发表自己的想法是个人自由 你个共产狗快滚回你国

呵呵，既然是自由干嘛这样骂人呢，一个不尊重个人一个不敢继续直面。GitHub是当前人类共有的社区，不是你个low B的地盘，你没有这个权力让我离开。早就拉黑你了，近期看到被一个鬼关注了，就找过来了，告诉你们，来一个拉黑一个。
