### ISSUE TITLE
剑桥美食需要更新一下了  Cambridge's got something new

### ISSUE THREAD

**Issue by brianpenghe** [cirosantilli/china-dictatorship#82]
天天 has opened up a second restaurant. Good food at lower price.
Spring.  The "spicy chicken with pasta and potatoes" should be 新疆大盘鸡？
Hong Kong Fusion.  It has two restaurants at Cambridge. 
There's also 江湖 next to 72 and 天天
There's a new 麻辣烫 restaurant opened on Regent street

Anyway these are not advertisements.
Welcome to come and try them.

**Comment by cirosantilli** [comment]
Brian,

Thanks! Finally someone posted an useful comment on this repo!!!

**Comment by brianpenghe** [comment]
> Brian,
> 
> Thanks! Finally someone posted an useful comment on this repo!!!

"a useful" issue  ; )
