### ISSUE TITLE
人们只有在翻墙挖掘并被真相震惊时才会看到真正的真相。作为一个半中国人半日本人，是的，我被洗脑了，因为不幸的是我出生在中国教育下，我从来没有过 google/reddit/discord 等的形象，直到我通过与朋友的日常对话介绍了一个 vpn，我 认为内容封锁在中国存在，然后它为自由的实际定义打开了新的大门。 tbh 我相信中国是一个如此统一的国家，直到我在推特上看到政府通常禁止的视频/音频，幸运的是我没有像其他发行人对这个回购所做的那样疯狂，很快我就意识到了一个事实 他妈的中国政府是多么腐败，尤其是对那些我永远没有机会经历的贫困社区，所以，是的，感谢您向公众分享和揭露这些事实，针对华人社区。 People don't see the actual truth until they dig crawl over the wall and being astonished by the truth

### ISSUE THREAD

**Issue by andatoshiki** [cirosantilli/china-dictatorship#833]
As a half Chinese and half Japanese, yes I get brainwashed since I was unfortunately born under Chinese education, I never had a figure of google/reddit/discord and etc until I got introduced to a vpn by a daily conversation with my friends and I leaned that contents blocking exists in China then it opened up a new gate out to the actual definition in terms of freedom. Tbh I believed China was such a unified nation untill I saw those commonly banned videos/audios by the government on twitter, luckily I didn't act out crazy like what other issuers did to this repo, soon I realized the fact that how shit and how fucked Chinese government is corrupted especially to those poor communities which I would never had chance to go through, so yes, thanks for sharing and revealing these facts to publics, targeting Chinese community.

- https://cirosantilli.com/china-dictatorship/most-chinese-people-like-their-dictatorship
- https://cirosantilli.com/china-dictatorship/chilling-effect
- https://cirosantilli.com/china-dictatorship/internal-censorship

**Comment by andatoshiki** [comment]
> Thanks! Stay safe! Frog in well meme is a must for this subject: https://cirosantilli.com/china-dictatorship/internal-censorship

Thanks you too :-)

**Comment by Lyc2001** [comment]
小杂种，下次学几句中文再来狗叫，别你妈逼发一堆机翻的脑瘫东西在这丢人现眼

**Comment by andatoshiki** [comment]
> 小杂种，下次学几句中文再来狗叫，别你妈逼发一堆机翻的脑瘫东西在这丢人现眼

In accordance with your abusive behavior with aggressive language choices in Chinese, I have already reported you to GitHub's anti-abuse report team, wait for your account get flagged on GitHub, :) yet I have already blocked your account for my GitHub using experience for not having interferences with you extreme patriotic Chinese user's angriness. And what's more funny you are using a Git version controlling platform developed by a third country and you are feeling angry with what all these so-called "foreigner's" attitudes & comments on your own country; don't put the horse behind the cart. If you would like to express your patriotism towards your country, don't use GitHub, use either Gitee or Coding as my advise, if you are using GitHub, bear.

Additional: I posted my original issue in English, the translation was done via Google Translation or other third party app by the repo owner for those of Chinese whom does not read English like an illiterate, no offense, stating truth.

**Comment by gittestkey** [comment]
> > 小杂种，下次学几句中文再来狗叫，别你妈逼发一堆机翻的脑瘫东西在这丢人现眼
> 
> In accordance with your abusive behavior with aggressive language choices in Chinese, I have already reported you to GitHub's anti-abuse report team, wait for your account get flagged on GitHub, :) yet I have already blocked your account for my GitHub using experience for not having interferences with you extreme patriotic Chinese user's angriness. And what's more funny you are using a Git version controlling platform developed by a third country and you are feeling angry with what all these so-called "foreigner's" attitudes & comments on your own country; don't put the horse behind the cart. If you would like to express your patriotism towards your country, don't use GitHub, use either Gitee or Coding as my advise, if you are using GitHub, bear.
> 
> Ask your self what is the main centralized reason for Chinese user not using China-made Git services? Why? Is it because of the lack of features like GitHub? No, it's because you are required to have your personal identity be verified with real documents for proceeding to the service. No verification, no service.
> 
> Additional: I posted my original issue in English, the translation was done via Google Translation or other third party app by the repo owner for those of Chinese whom does not read English like an illiterate, no offense, stating truth.

This repo can exist, do you think report can work?
you are really funny 扎泼腻籽
油骂母诶子带的。
油啊额扎泼腻籽 嗖油啊额恶麦瑞卡道ge
