### ISSUE TITLE
为什么不禁用问题选项卡？ 为什么不禁用此 repo 的问题选项卡，因为它更多地作为基于 GitHub 的 wiki 系统提供功能？ 而不是看着所有这些爱国的中国问题发表这些负面评论？ Why not disable issue tab? Why not disable issue tab for this repo, since it more serves a feature as a wiki system based off GitHub? Instead of watching all these patriotic Chinese issues out these negative comments?

### ISSUE THREAD

**Issue by andatoshiki** [cirosantilli/china-dictatorship#838]
Reply: Rationale currently given at: https://github.com/cirosantilli/china-dictatorship/blob/61beb1d62d86a8173723cd484e0f8f6ddfe5107c/CONTRIBUTING.md

Furthermore, not banning such users has the following advantages:

it serves as a clear demonstration of the level of radicalization of some pro-Chinese Government believers, which many people in the West haven't fully grasped
when China becomes a democracy, such issues will help secret services/activist groups expose the true identities of these people
Also, it gives me some sense if this project is having an effect or not.

**Comment by cirosantilli** [comment]
Rationale currently given at: https://github.com/cirosantilli/china-dictatorship/blob/61beb1d62d86a8173723cd484e0f8f6ddfe5107c/CONTRIBUTING.md

> Furthermore, not banning such users has the following advantages:
>
> - it serves as a clear demonstration of the level of radicalization of some pro-Chinese Government believers, which many people in the West haven't fully grasped
> - when China becomes a democracy, such issues will help secret services/activist groups expose the true identities of these people

Also, it gives me some sense if this project is having an effect or not.
