### ISSUE TITLE
You are pursuing Chinese government to block github 

### ISSUE THREAD

**Issue by NooooWorries** [cirosantilli/china-dictatorship#9]
I can’t understands why u guys post such articles on a technical tools. 
MOST Programmers in China rely on Github to develop softwares.
BUT YOUR BEHAVIOUR IS TRY TO PUSH CHINESE GOVERNMENT TO BLOCK GITHUB.
So I can say, YOU put Chinese programmers in big trouble.

**Comment by cirosantilli** [comment]
https://github.com/cirosantilli/china-dictatorship/blob/3f3afbec19ee8c35d5d6020a2662b269e3859f06/FAQ.md#why-are-you-attacking-websites-with-censored-keywords

https://github.com/cirosantilli/china-dictatorship/blob/3f3afbec19ee8c35d5d6020a2662b269e3859f06/FAQ.md#this-is-your-personal-problem-we-have-nothing-to-do-with-it-stop-punishing-us-for-it
