### ISSUE TITLE
You Should Live in China for Some Time 

### ISSUE THREAD

**Issue by Eralien** [cirosantilli/china-dictatorship#93]
I used to believe in a lot of bullshit stuff about how efficient democracy in US enables the mass and benefit everyone, and how awful CCP is. No. After living in USA for  a few years, my view has totally changed. I realize what I learnt from the politics textbooks in China was not propaganda bullshit, but is fucking true in many ways.

So why don't you visit China and lived for at least 6 months? But if all you believe is that you are gonna got persecuted by CCP if you are in China, then I got nothing to say. You simply cannot argue with a person, if all he get is religious mentality and missionary enthusiasm and no bravery to dive into the other side and seek the truth. If this is the case, what's your difference from those red guards during the cultural revolution who devoted to believe the west was cancer of humanity?

I highly recommend you considering my suggestion seriously. It would add up to your credibility when you talk about China in the future.

**Comment by cirosantilli** [comment]
Not worth my time and risk of not getting visa or getting there and being sent back at border, please just explain more precisely what you learnt by living there.

**Comment by PinoTsao** [comment]
楼主 is ignorant because he hasn't really lead a life as a worker in the mainland, and he don't have good cognition ability about the life there.
As someone said, that democracy system in US is not flawless, but the one works best until now. It is not heaven, it's you, who don't have the real ability to thinking, think US is the heaven.

You don't think it is good? Welcome back

**Comment by Eralien** [comment]
> 楼主 is ignorant because he hasn't really lead a life as a worker in the mainland, and he don't have good cognition ability about the life there.
> As someone said, that democracy system in US is not flawless, but the one works best until now. It is not heaven, it's you, who don't have the real ability to thinking, think US is the heaven.
> 
> You don't think it is good? Welcome back

I am back in China now. I feel incredibly safe. I am free from coronavirus. Yet your "works best" regime kills more than 100k people in the pandemic. Please do not make Github looks like Trump's twitter.

**Comment by PinoTsao** [comment]
Please be reasonable, Please don't spew the non-sense like propaganda outlet: "work best among all" is comprehensive, but you just focus on the virus, cognitive flaw.

Wish you won't meet the socialism iron fist, good luck

不要习惯了黑暗，就赞美黑暗。当然，可能你并没有看到黑暗

**Comment by Eralien** [comment]
Very rude and childish to say someone has cognitive flaw while you might not even understand what is cognition. Your quotes extremely resonates with bullshit used to fool high school kids in China, you know, a meaningless yet poetic sentence, which proves nothing but inflict emotions in naive minds. I read serious political philosophy. 

For instance, would you mind explain why you say "socialism" iron fist? Why not capitalist iron fist? Why not fascism? Why not commercialism? Why not communism? What do you think defines "socialism"? India is a socialist republic by its definition, and what do you make of that?

Furthermore, can you explain to me what constitutes democracy and liberalism? What do you really mean by using these words?

**Comment by PinoTsao** [comment]
"rude"? "childish"? if you think so~ 忠言的确逆耳。For me, that is not "meaningless poetic sentence", it is from my life experience, causing resonance to me. Actually, I don't think reading lots of books like "serious political philosophy" means too much for me, you definitely know there are examples of illiteracy women who won't bothered to be great moms. Reading that much doesn't mean one has integrity, good outlook, right?

Looking at your questions, what a bunch of rhetoric, 胡搅蛮缠可不好～ Did you ever heard of those "** iron fists" except "socialism"? that is not coined by me, OK? If you don't, I guess you are of 1990s generation.

Finally, you misunderstand me, I don't really care politics, democracy, liberalism,  I care my rights, especially freedom. You are good, Tsinghua elite, huh, means you seldom come across the low level shit of factory workers, Did you hear of 雷洋 of 人大?

Anyway, let's stop this argument, we don't have chance to persuade the other. Good luck

**Comment by PinoTsao** [comment]
最后，我想描述下看过您的回复，我的感受，Not focusing the content itself.

读过严肃政治哲学，一堆看似困难的问题，玩知识碾压？bully 没有上过清华的普通同学？毕竟清华高才，IQ拔萃，无法理解数理化不好的同学为什么学不好数理化。Seems like flaunting your talent.

这种行为看起来很 Chinese. 仗 talent 欺人？
不理解异见者的感受，也没兴趣去理解别人为什么会这样感受，而我觉得这才是有意思的话题。High IQ !=  right value, righteous, having empathy, etc.
