### ISSUE TITLE
How to reporting abuse or spam

### ISSUE THREAD

**Issue by ShineSmile** [cirosantilli/china-dictatorship#94]
https://help.github.com/en/github/building-a-strong-community/reporting-abuse-or-spam#about-reporting-abuse-or-spam

**Comment by cirosantilli** [comment]
Hi Shine,

For some reason I didn't get notified for this.

If anyone violates this repo's https://github.com/cirosantilli/china-dictatorship/blob/master/CONTRIBUTING.md notably generating lots of useless notifications, do at mention me and I'll block the user.

If it's about reporting this repo, feel free to CC me by creating an issue in this repo saying why you think this repo should be taken down by GitHub.

**Comment by ShineSmile** [comment]
我不知道你有什么阴谋或者动机。
只觉得你很无聊脏了我的眼。
你有言论自由的权力，但请别在GitHub上没事找事可以吗。
想表达你的意见有新闻平台等媒体，这里是技术社区，你来错地方了。

**Comment by ShineSmile** [comment]
issue我关了。
懒得和你这种狭隘的人交流。
