### ISSUE TITLE
领导留言板欢迎您

### ISSUE THREAD

**Issue by xulis** [cirosantilli/china-dictatorship#95]
首先非常感谢大家关注中国的民主化建设，我们非常乐意听取大家的建议和意见。
尽管我们的网络问责通道还有待完善，不过目前已经有一些不错的选择：

人民网的领导留言板： http://liuyan.people.com.cn/home

我在上面反映了家乡（偏远山区）网络不好的问题， 很快政府就安排部署了4G网络基站，我觉得大家若有什么问题都可以反映上去，希望可以帮到你。

顺颂时祺。

**Comment by cirosantilli** [comment]
Thanks for the link,

I wonder how long it would take for a post on a censored subject to be taken down from a People's Daily website, e.g. "disable the firewall". It would be a fun experiment.

https://github.com/cirosantilli/china-dictatorship#biased-media

**Comment by xulis** [comment]
作为一名IT从业者，我也甚是讨厌GFW，它就如同外国媒体蒙住外国人民的眼睛一样蒙住我的眼睛。
当一个国家还不够强大的时候，它的自卫措施就能体现出来，我们也期待有一天我们能强大到无需任何防火墙。
只是现在，要解除这种国家安全设施，就好像关闭棱镜项目一样艰难呐。
https://zh.wikipedia.org/wiki/%E7%A8%9C%E9%8F%A1%E8%A8%88%E7%95%AB
